<button id="button">
    <span><?php echo $escaper->escapeHtml($block->getClick()) ?></span>
</button>

<div id="modal">
    <div class="modal-body-content">
        <h2><?php echo $escaper->escapeHtml($block->getTitle()) ?></h2>
        <p><?php echo $escaper->escapeHtml($block->getContent()) ?></p>
    </div>
</div>

<script type="text/javascript">
    require([
        "jquery",
        "Magento_Ui/js/modal/modal"
    ],function($, modal) {

        var options = {
            type: 'popup',
            responsive: true,
            title: 'Main title',
            buttons: [{
                text: $.mage.__('Ok'),
                class: '',
                click: function () {
                    this.closeModal();
                }
            }]
        };

        var popup = modal(options, $('#modal'));
        $("#button").click(function() {
            $('#modal').modal('openModal');
        });
    });
</script>


